export const assetData = [
    { ticker: 'AAPL', price: 150, category: 'Tech', marketCap: '2.4T', sector: 'Information Technology', peRatio: 28.57 },
    { ticker: 'GOOGL', price: 2800, category: 'Tech', marketCap: '1.9T', sector: 'Communication Services', peRatio: 30.25 },
    { ticker: 'AMZN', price: 3400, category: 'E-commerce', marketCap: '1.6T', sector: 'Consumer Discretionary', peRatio: 60.50 },
    { ticker: 'MSFT', price: 299, category: 'Tech', marketCap: '2.2T', sector: 'Information Technology', peRatio: 35.45 },
    { ticker: 'TSLA', price: 800, category: 'Automotive', marketCap: '800B', sector: 'Consumer Discretionary', peRatio: 100.52 },
    { ticker: 'NFLX', price: 550, category: 'Entertainment', marketCap: '240B', sector: 'Communication Services', peRatio: 45.67 },
    { ticker: 'NVDA', price: 720, category: 'Tech', marketCap: '400B', sector: 'Information Technology', peRatio: 90.21 },
    { ticker: 'INTC', price: 52, category: 'Tech', marketCap: '210B', sector: 'Information Technology', peRatio: 12.45 },
    { ticker: 'AMD', price: 95, category: 'Tech', marketCap: '110B', sector: 'Information Technology', peRatio: 50.98 },
    { ticker: 'DIS', price: 170, category: 'Entertainment', marketCap: '320B', sector: 'Communication Services', peRatio: 20.45 },
    { ticker: 'BA', price: 215, category: 'Aerospace', marketCap: '120B', sector: 'Industrials', peRatio: 35.76 },
    { ticker: 'KO', price: 56, category: 'Food & Beverage', marketCap: '250B', sector: 'Consumer Staples', peRatio: 22.15 },
    { ticker: 'PEP', price: 149, category: 'Food & Beverage', marketCap: '220B', sector: 'Consumer Staples', peRatio: 24.19 },
    { ticker: 'T', price: 29, category: 'Telecom', marketCap: '160B', sector: 'Communication Services', peRatio: 11.45 },
    { ticker: 'VZ', price: 58, category: 'Telecom', marketCap: '190B', sector: 'Communication Services', peRatio: 13.87 },
    { ticker: 'JPM', price: 155, category: 'Finance', marketCap: '500B', sector: 'Financials', peRatio: 12.98 },
    { ticker: 'BAC', price: 43, category: 'Finance', marketCap: '330B', sector: 'Financials', peRatio: 10.52 },
    { ticker: 'WMT', price: 142, category: 'Retail', marketCap: '410B', sector: 'Consumer Staples', peRatio: 23.67 },
    { ticker: 'COST', price: 470, category: 'Retail', marketCap: '230B', sector: 'Consumer Staples', peRatio: 38.23 },
    { ticker: 'HD', price: 310, category: 'Home Improvement', marketCap: '350B', sector: 'Consumer Discretionary', peRatio: 25.12 },
    { ticker: 'LOW', price: 205, category: 'Home Improvement', marketCap: '130B', sector: 'Consumer Discretionary', peRatio: 22.98 },
    { ticker: 'CVX', price: 103, category: 'Energy', marketCap: '190B', sector: 'Energy', peRatio: 18.65 },
    { ticker: 'XOM', price: 88, category: 'Energy', marketCap: '300B', sector: 'Energy', peRatio: 14.29 },
    { ticker: 'MCD', price: 232, category: 'Food & Beverage', marketCap: '180B', sector: 'Consumer Discretionary', peRatio: 35.45 },
    { ticker: 'SBUX', price: 112, category: 'Food & Beverage', marketCap: '140B', sector: 'Consumer Discretionary', peRatio: 30.56 },
    { ticker: 'NKE', price: 147, category: 'Apparel', marketCap: '200B', sector: 'Consumer Discretionary', peRatio: 40.12 },
    { ticker: 'ADBE', price: 515, category: 'Tech', marketCap: '250B', sector: 'Information Technology', peRatio: 55.76 },
    { ticker: 'CRM', price: 238, category: 'Tech', marketCap: '220B', sector: 'Information Technology', peRatio: 45.89 },
    { ticker: 'ORCL', price: 77, category: 'Tech', marketCap: '200B', sector: 'Information Technology', peRatio: 20.65 },
    { ticker: 'PYPL', price: 234, category: 'Finance', marketCap: '280B', sector: 'Financials', peRatio: 65.45 },
    { ticker: 'SQ', price: 260, category: 'Finance', marketCap: '120B', sector: 'Financials', peRatio: 75.30 },
    { ticker: 'V', price: 230, category: 'Finance', marketCap: '500B', sector: 'Financials', peRatio: 32.10 },
    { ticker: 'MA', price: 355, category: 'Finance', marketCap: '350B', sector: 'Financials', peRatio: 42.55 },
    { ticker: 'EBAY', price: 65, category: 'E-commerce', marketCap: '43B', sector: 'Consumer Discretionary', peRatio: 16.87 },
    { ticker: 'SHOP', price: 1200, category: 'E-commerce', marketCap: '150B', sector: 'Consumer Discretionary', peRatio: 110.15 },
  ];
  